[versions]
android-minSdk = "26"
android-compileSdk = "35"
android-targetSdk = "35"

androidGradlePlugin = "8.6.0"
androidx-activity-compose = "1.9.1"
androidx-window = "1.3.0"
compose-plugin = "1.7.0-alpha03"
haze = "0.9.0-alpha08"
kotlin = "2.0.20"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "androidx-window" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }